setup-screens: Screens for bottom

diff --git a/setup-screens b/setup-screens
--- a/setup-screens
+++ b/setup-screens
@@ -1,10 +1,9 @@
 #!/bin/bash
 
-xrandr --output DVI-I-1 --mode 1920x1080
-if [ -n "$X_ONE_SCREEN" ]; then
-	xrandr --output DVI-D-0 --off
-	xrandr --output HDMI-0 --off
-else
-	xrandr --output DVI-D-0 --mode 1920x1080 --rotate left --pos 1920x-420
-	xrandr --output HDMI-0 --mode 1080x1920 --rotate left --right-of DVI-D-0 # Oculus Rift
+xrandr --output eDP2 --mode 1920x1080
+	for screen in DP1 DP2 HDMI1 HDMI2 VGA1 VIRTUAL1; do
+		xrandr --output "$screen" --off
+	done
+if [ -z "$X_ONE_SCREEN" ]; then
+	xrandr --output VGA1 --mode 2048x1152 --pos 1920x0 || true # may fail if not connected
 fi
