youtube-dl-music: Retry failure when trying to autopath

diff --git a/youtube-dl-music b/youtube-dl-music
--- a/youtube-dl-music
+++ b/youtube-dl-music
@@ -10,7 +10,11 @@ AUTOPATH_SCRIPT=${AUTOPATH_SCRIPT:-~/.youtube-dl-music-autopath}
 
 if [ -z "$DEST" ] && [ -x "$AUTOPATH_SCRIPT" ]; then
 	echo "Attempting to autopath"
-	autopath_output="$(youtube-dl --dump-json  -- "$@"| $AUTOPATH_SCRIPT)"
+	for x in `seq 3`; do
+		autopath_input="$(youtube-dl --dump-json  -- "$@")" && break
+	done
+	[ -n "$autopath_input" ] || echo "Failed to get info for autopath - trying anyway"
+	autopath_output="$($AUTOPATH_SCRIPT <<<"$autopath_input")"
 	if [ $? -eq 0 ] && [ -n "$autopath_output" ]; then
 		DEST="$autopath_output"
 		echo "Using autopath: $autopath_output"
